version: '3.11'

services:
  web:
    image: auth_app
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  
    volumes:
      - .:/auth_app
    ports:
      - "8000:8000"